=== TheHollowEsp/DAIDocServer/Proyecto/src/test/es/uvigo/esei/dai/hybridserver/week7/sample2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.esei.uvigo.es/dai/proyecto"
	xmlns:tns="http://www.esei.uvigo.es/dai/proyecto">
	<element name="collection">
		<complexType>
			<sequence>
				<element name="disc" type="tns:disc" minOccurs="0" maxOccurs="unbounded"/>
				<element name="movie" type="tns:movie" minOccurs="0" maxOccurs="unbounded"/>
				<element name="book" type="tns:book" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>

    <complexType name="item">
    	<sequence>
    		<element name="name" type="string"/>
    	</sequence>
   		<attribute name="year" type="unsignedInt"/>
    </complexType>

    <complexType name="disc">
    	<complexContent>
    		<extension base="tns:item">
    			<sequence>
    				<element name="genre" type="string"/>
    				<element name="artist" type="string"/>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="movie">
    	<complexContent>
    		<extension base="tns:item">
    			<sequence>
    				<element name="genre" type="string"/>
    				<element name="director" type="string"/>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="book">
    	<complexContent>
    		<extension base="tns:item">
    			<sequence>
    				<element name="genre" type="string"/>
    				<element name="author" type="string"/>
    				<element name="pages" type="unsignedInt"/>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
</schema>

=== TheHollowEsp/DAIDocServer/Proyecto/src/test/es/uvigo/esei/dai/hybridserver/week9/sample2.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:collection xmlns:tns="http://www.esei.uvigo.es/dai/proyecto"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.esei.uvigo.es/dai/proyecto sample2.xsd ">
	<disc year="1972">
		<name>Live in Japan</name>
		<genre>Hard Rock</genre>
		<artist>Deep Purple</artist>
	</disc>
	<disc year="1972">
		<name>Led Zeppelin</name>
		<genre>Hard Rock</genre>
		<artist>Led Zeppelin</artist>
	</disc>
	<disc year="1990">
		<name>Shake Your Money Maker</name>
		<genre>Southern Rock</genre>
		<artist>The Black Crowes</artist>
	</disc>
	
	<movie year="1972">
		<name>The Godfather</name>
		<genre>Drama</genre>
		<director>Francis Ford Coppola</director>
	</movie>
	<movie>
		<name>Interstellar</name>
		<genre>Adventure</genre>
		<director>Christopher Nolan</director>
	</movie>
	
	<book year="1965">
		<name>Dune</name>
		<genre>Science Fiction</genre>
		<author>Frank Herbert</author>
		<pages>412</pages>
	</book>
	<book year="1922">
		<name>Siddhartha</name>
		<genre>Novel</genre>
		<author>Hermann Hesse</author>
		<pages>152</pages>
	</book>
</tns:collection>
