=== TheHollowEsp/DAIDocServer/Proyecto/src/test/es/uvigo/esei/dai/hybridserver/week11/files/dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT dataset (HTML+,XML+,XSD+,XSLT+)>
<!ELEMENT HTML EMPTY>
<!ATTLIST HTML
	uuid CDATA #REQUIRED
	content CDATA #REQUIRED
>
<!ELEMENT XML EMPTY>
<!ATTLIST XML
	uuid CDATA #REQUIRED
	content CDATA #REQUIRED
>
<!ELEMENT XSD EMPTY>
<!ATTLIST XSD
	uuid CDATA #REQUIRED
	content CDATA #REQUIRED
>
<!ELEMENT XSLT EMPTY>
<!ATTLIST XSLT
	uuid CDATA #REQUIRED
	xsd CDATA #REQUIRED
	content CDATA #REQUIRED
>

=== TheHollowEsp/DAIDocServer/Proyecto/src/test/es/uvigo/esei/dai/hybridserver/week3/dataset.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "dataset.dtd" >
<dataset>
	<HTML uuid="6df1047e-cf19-4a83-8cf3-38f5e53f7725"
		content="&lt;html&gt;&lt;body&gt;This is the html page 6df1047e-cf19-4a83-8cf3-38f5e53f7725.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="79e01232-5ea4-41c8-9331-1c1880a1d3c2"
		content="&lt;html&gt;&lt;body&gt;This is the html page 79e01232-5ea4-41c8-9331-1c1880a1d3c2.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="a35b6c5e-22d6-4707-98b4-462482e26c9e"
		content="&lt;html&gt;&lt;body&gt;This is the html page a35b6c5e-22d6-4707-98b4-462482e26c9e.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="3aff2f9c-0c7f-4630-99ad-27a0cf1af137"
		content="&lt;html&gt;&lt;body&gt;This is the html page 3aff2f9c-0c7f-4630-99ad-27a0cf1af137.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="77ec1d68-84e1-40f4-be8e-066e02f4e373"
		content="&lt;html&gt;&lt;body&gt;This is the html page 77ec1d68-84e1-40f4-be8e-066e02f4e373.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="8f824126-0bd1-4074-b88e-c0b59d3e67a3"
		content="&lt;html&gt;&lt;body&gt;This is the html page 8f824126-0bd1-4074-b88e-c0b59d3e67a3.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="c6c80c75-b335-4f68-b7a7-59434413ce6c"
		content="&lt;html&gt;&lt;body&gt;This is the html page c6c80c75-b335-4f68-b7a7-59434413ce6c.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="f959ecb3-6382-4ae5-9325-8fcbc068e446"
		content="&lt;html&gt;&lt;body&gt;This is the html page f959ecb3-6382-4ae5-9325-8fcbc068e446.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="2471caa8-e8df-44d6-94f2-7752a74f6819"
		content="&lt;html&gt;&lt;body&gt;This is the html page 2471caa8-e8df-44d6-94f2-7752a74f6819.&lt;/body&gt;&lt;/html&gt;" />
	<HTML uuid="fa0979ca-2734-41f7-84c5-e40e0886e408"
		content="&lt;html&gt;&lt;body&gt;This is the html page fa0979ca-2734-41f7-84c5-e40e0886e408.&lt;/body&gt;&lt;/html&gt;" />
</dataset>
